### ISSUE TITLE
Add information on where to get tested

### ISSUE THREAD

**Issue by bodhish** [coronasafe/coronasafe.in#16]
- [ ] List of hospitals (state wise)
- [ ] Any relevent details on the procedure

**Comment by arshankar07** [comment]
Source: https://icmr.nic.in/content/covid-19
List of testing sites, state-wise (52) : https://icmr.nic.in/sites/default/files/upload_documents/Testing_sites_for_COVID19.pdf
List of sample collection labs, state-wise (57) : 
https://icmr.nic.in/sites/default/files/upload_documents/Sample_Collection_Lab_COVID19.pdf
List of VRDLs and their contacts:
https://icmr.nic.in/sites/default/files/upload_documents/List_of_VRDL_V2.pdf
COViD Testing Strategy (Evolving):
https://icmr.nic.in/sites/default/files/upload_documents/Advisory_COVID19_9Mar2020.pdf
Laboratory Preparedness :
https://icmr.nic.in/sites/default/files/press_realease_files/ICMR_PressRelease_COVID_19.pdf

**Comment by aswinmohanme** [comment]
Fixed by #19
