### ISSUE TITLE
Add content for the I'm Infected Section

### ISSUE THREAD

**Issue by aswinmohanme** [coronasafe/coronasafe.in#2]
Add content for the https://www.coronasafe.in/action/i-am-infected page. The major source is https://www.cdc.gov/coronavirus/2019-ncov/about/steps-when-sick.html

**Comment by bodhish** [comment]
https://github.com/coronasafe/coronasafe.in/commit/f754b8d9727199569b9616b8fb7e3a95e2524b0a

**Comment by aswinmohanme** [comment]
This commit fixes #3 we need to fix this issue too

**Comment by rejuls** [comment]
I'm working on it
