### ISSUE TITLE
The map shows wrong info about the number of cases

### ISSUE THREAD

**Issue by MansoorMajeed** [coronasafe/coronasafe.in#32]
![Screenshot 2020-03-23 at 10 44 10 AM](https://user-images.githubusercontent.com/12676196/77283837-50ff9000-6cf3-11ea-84bf-d7e6086427bf.png)

Number of cases is the same as number of observations. Not sure if this is intended behaviour

**Comment by athuljayaraj** [comment]
@bodhish Looks like the issue has been resolved.

<img width="339" alt="Screenshot 2020-03-23 at 6 59 50 PM" src="https://user-images.githubusercontent.com/7582620/77321653-7ebaf800-6d38-11ea-8572-3e896a85181d.png">

**Comment by bodhish** [comment]
Closing the issue
