### ISSUE TITLE
Add section for live updates on the spread

### ISSUE THREAD

**Issue by Ascalonic** [coronasafe/coronasafe.in#7]
A section to view the current active cases of Coronavirus in India. Most internationally available sources are too broad and aren't localized.

**Comment by aswinmohanme** [comment]
That would require constant updates if we stick with the static page.

**Comment by bodhish** [comment]
@aswinmohanme @ascalonic gitbooks supports `API calls`. I am not sure if that would be useful.
If that doesn't work out. We could use `http://stopcorona.live` to track this.

(we have the domain)
